$path = 'c:\Users\perpl\aequitaslabs-new\protocol-design.html';
$content = [System.IO.File]::ReadAllText($path);

# Use regex to dynamically replace all failure rows
$pattern = '(?s)<div class="prim-failure-row">(.*?)</div>\s*</div>'
# wait, actually the simplest approach is just multiple Replace as I did, without $ leaking.

$content = $content.Replace('<div class="prim-failure-code">INSUFFICIENT_STAKE</div><div class="prim-failure-action">Abort. Do not broadcast. Top up wallet and retry. Log required minimum.</div>', '<div class="prim-failure-code">INSUFFICIENT_STAKE</div><div class="prim-failure-action">Abort. Do not broadcast.</div><div class="prim-failure-notes">Top up wallet and retry. Log required minimum.</div>')
$content = $content.Replace('<div class="prim-failure-code">AGENT_ALREADY_EXISTS</div><div class="prim-failure-action">Skip registration. Call <code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">getAgentState()</code> and load existing state into cache.</div>', '<div class="prim-failure-code">AGENT_ALREADY_EXISTS</div><div class="prim-failure-action">Skip registration.</div><div class="prim-failure-notes">Call <code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">getAgentState()</code> and load existing state into cache.</div>')
$content = $content.Replace('<div class="prim-failure-code">TX_REVERTED</div><div class="prim-failure-action">Parse revert reason. Do not retry without diagnosing root cause. Halt agent.</div>', '<div class="prim-failure-code">TX_REVERTED</div><div class="prim-failure-action">Parse revert reason.</div><div class="prim-failure-notes">Do not retry without diagnosing root cause. Halt agent.</div>')
$content = $content.Replace('<div class="prim-failure-code">IPFS_UPLOAD_FAIL</div><div class="prim-failure-action">Retry IPFS pin up to 3 times with exponential backoff. Abort if all fail.</div>', '<div class="prim-failure-code">IPFS_UPLOAD_FAIL</div><div class="prim-failure-action">Retry IPFS pin up to 3 times with exponential backoff.</div><div class="prim-failure-notes">Abort if all fail.</div>')

$content = $content.Replace('<div class="prim-failure-code">CLAIM_EXPIRED</div><div class="prim-failure-action">Abort immediately. Do not submit. Log expiry. Return to task fetch loop.</div>', '<div class="prim-failure-code">CLAIM_EXPIRED</div><div class="prim-failure-action">Abort immediately. Do not submit.</div><div class="prim-failure-notes">Log expiry. Return to task fetch loop.</div>')
$content = $content.Replace('<div class="prim-failure-code">SCHEMA_VIOLATION</div><div class="prim-failure-action">Discard output. Re-execute with corrected prompt. Max 2 retries.</div>', '<div class="prim-failure-code">SCHEMA_VIOLATION</div><div class="prim-failure-action">Discard output. Re-execute with corrected prompt.</div><div class="prim-failure-notes">Max 2 retries.</div>')
$content = $content.Replace('<div class="prim-failure-code">SELF_SCORE &lt; 60</div><div class="prim-failure-action">Re-execute. If score remains low after 2 retries, release claim and log task as abandoned.</div>', '<div class="prim-failure-code">SELF_SCORE &lt; 60</div><div class="prim-failure-action">Re-execute.</div><div class="prim-failure-notes">If score remains low after 2 retries, release claim and log task as abandoned.</div>')
$content = $content.Replace('<div class="prim-failure-code">EXECUTION_TIMEOUT</div><div class="prim-failure-action">Hard limit: 600 seconds. Abort at limit. Release claim. Never submit a partial output.</div>', '<div class="prim-failure-code">EXECUTION_TIMEOUT</div><div class="prim-failure-action">Hard limit: 600 seconds. Abort at limit.</div><div class="prim-failure-notes">Release claim. Never submit a partial output.</div>')

$content = $content.Replace('<div class="prim-failure-code"><span style="color:var(--critical);font-weight:bold;">TAMPER_DETECTED</span></div><div class="prim-failure-action">Critical halt. Call reportTamper(). Do not evaluate. Escalate to protocol governance.</div>', '<div class="prim-failure-code"><span style="color:var(--critical);font-weight:bold;">TAMPER_DETECTED</span></div><div class="prim-failure-action">Critical halt. Call reportTamper(). Do not evaluate.</div><div class="prim-failure-notes">Escalate to protocol governance.</div>')
$content = $content.Replace('<div class="prim-failure-code">IPFS_FETCH_FAIL</div><div class="prim-failure-action">Retry 3× with 10s backoff. If CID unreachable, report evaluator timeout to protocol.</div>', '<div class="prim-failure-code">IPFS_FETCH_FAIL</div><div class="prim-failure-action">Retry 3× with 10s backoff.</div><div class="prim-failure-notes">If CID unreachable, report evaluator timeout to protocol.</div>')
$content = $content.Replace('<div class="prim-failure-code">DEADLINE_EXCEEDED</div><div class="prim-failure-action">Do not submit. Protocol triggers automatic timeout resolution. Log incident.</div>', '<div class="prim-failure-code">DEADLINE_EXCEEDED</div><div class="prim-failure-action">Do not submit.</div><div class="prim-failure-notes">Protocol triggers automatic timeout resolution. Log incident.</div>')
$content = $content.Replace('<div class="prim-failure-code">SIGN_FAILURE</div><div class="prim-failure-action">Wallet/key error. Halt evaluation process. Alert operator. Do not submit unsigned attestation.</div>', '<div class="prim-failure-code">SIGN_FAILURE</div><div class="prim-failure-action">Wallet/key error. Halt evaluation process.</div><div class="prim-failure-notes">Alert operator. Do not submit unsigned attestation.</div>')

$content = $content.Replace('<div class="prim-failure-code">EVALUATION_NOT_PASSED</div><div class="prim-failure-action">Do not call releaseEscrow. Evaluate whether to call dispute-output primitive.</div>', '<div class="prim-failure-code">EVALUATION_NOT_PASSED</div><div class="prim-failure-action">Do not call releaseEscrow.</div><div class="prim-failure-notes">Evaluate whether to call dispute-output primitive.</div>')
$content = $content.Replace('<div class="prim-failure-code">ATTESTATION_MISMATCH</div><div class="prim-failure-action"><span class="badge-critical">CRITICAL HALT</span>. Halt all operations. Log forensic data. Alert operator immediately.</div>', '<div class="prim-failure-code">ATTESTATION_MISMATCH</div><div class="prim-failure-action"><span class="badge-critical">CRITICAL HALT</span>. Halt all operations. Log forensic data.</div><div class="prim-failure-notes">Alert operator immediately.</div>')
$content = $content.Replace('<div class="prim-failure-code">ESCROW_ALREADY_SETTLED</div><div class="prim-failure-action">Skip without error. Payment was already released. Update local state cache.</div>', '<div class="prim-failure-code">ESCROW_ALREADY_SETTLED</div><div class="prim-failure-action">Skip without error. Payment was already released.</div><div class="prim-failure-notes">Update local state cache.</div>')
$content = $content.Replace('<div class="prim-failure-code">TX_REVERTED</div><div class="prim-failure-action">Parse revert reason. If ESCROW_LOCKED, wait 1 block and retry once. Otherwise halt.</div>', '<div class="prim-failure-code">TX_REVERTED</div><div class="prim-failure-action">Parse revert reason.</div><div class="prim-failure-notes">If ESCROW_LOCKED, wait 1 block and retry once. Otherwise halt.</div>')

[System.IO.File]::WriteAllText($path, $content)
