$path = "c:\Users\perpl\aequitaslabs-new\protocol-design.html"
$content = [System.IO.File]::ReadAllText($path)

$content = $content.Replace('0.05 ETH', '0.01 ETH')
$content = $content.Replace('{value: 0.05}', '{value: 0.01}')
$content = $content.Replace('{value: <span class="ex-val">0.05</span>}', '{value: <span class="ex-val">0.01</span>}')
$content = $content.Replace('escrow_bal == <span class="ex-val">0.05 ETH</span>', 'escrow_bal == <span class="ex-val">0.01 ETH</span>')
$content = $content.Replace('<span class="ex-key">amount</span>     → <span class="ex-val">0.05 ETH</span>', '<span class="ex-key">amount</span>     → <span class="ex-val">0.01 ETH</span>')

# execute-task inputs
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">task_id</div><div class="prim-input-desc">Protocol task identifier from claimed TaskObject.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">task_id</div><div class="prim-input-type">bytes32</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Protocol task identifier from claimed TaskObject.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">task_description</div><div class="prim-input-desc">Full task instruction string. Passed directly as agent prompt.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">task_description</div><div class="prim-input-type">string</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Full task instruction string. Passed directly as agent prompt.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">criteria[]</div><div class="prim-input-desc">Evaluation criteria. Output must satisfy all entries.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">criteria[]</div><div class="prim-input-type">string[]</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Evaluation criteria. Output must satisfy all entries.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">output_format</div><div class="prim-input-desc"><code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">text</code> | <code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">json</code> | <code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">bytes</code> | <code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">ipfs_cid</code></div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">output_format</div><div class="prim-input-type">enum</div><div class="prim-input-req req">required</div><div class="prim-input-desc"><code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">text</code> | <code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">json</code> | <code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">bytes</code> | <code style="font-family:''DM Mono'',monospace;font-size:10px;color:var(--gold);">ipfs_cid</code></div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">claim_expiry</div><div class="prim-input-desc">Unix timestamp. Deadline for output submission. Monitor continuously.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">claim_expiry</div><div class="prim-input-type">uint256</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Unix timestamp. Deadline for output submission. Monitor continuously.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">context</div><div class="prim-input-desc">Additional context payload from client. Appended to prompt.</div><div class="prim-input-req opt">optional</div></div>', '<div class="prim-input-row"><div class="prim-input-name">context</div><div class="prim-input-type">bytes</div><div class="prim-input-req opt">optional</div><div class="prim-input-desc">Additional context payload from client. Appended to prompt.</div></div>')

# verify-proof inputs
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">submission_id</div><div class="prim-input-desc">Protocol-assigned ID from the OutputSubmitted event.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">submission_id</div><div class="prim-input-type">bytes32</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Protocol-assigned ID from the OutputSubmitted event.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">output_hash</div><div class="prim-input-desc">On-chain committed hash. Evaluator recomputes independently to verify.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">output_hash</div><div class="prim-input-type">bytes32</div><div class="prim-input-req req">required</div><div class="prim-input-desc">On-chain committed hash. Evaluator recomputes independently to verify.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">output_cid</div><div class="prim-input-desc">IPFS CID to fetch actual output bytes for evaluation.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">output_cid</div><div class="prim-input-type">string</div><div class="prim-input-req req">required</div><div class="prim-input-desc">IPFS CID to fetch actual output bytes for evaluation.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">criteria[]</div><div class="prim-input-desc">Same criteria array from the original task. Used as evaluation rubric.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">criteria[]</div><div class="prim-input-type">string[]</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Same criteria array from the original task. Used as evaluation rubric.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">evaluator_address</div><div class="prim-input-desc">Evaluator agent''s wallet. Signs the attestation payload.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">evaluator_address</div><div class="prim-input-type">address</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Evaluator agent''s wallet. Signs the attestation payload.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">score_weights</div><div class="prim-input-desc">Per-criterion weight array. Defaults to equal weighting.</div><div class="prim-input-req opt">optional</div></div>', '<div class="prim-input-row"><div class="prim-input-name">score_weights</div><div class="prim-input-type">float[]</div><div class="prim-input-req opt">optional</div><div class="prim-input-desc">Per-criterion weight array. Defaults to equal weighting.</div></div>')

# settle-escrow inputs
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">submission_id</div><div class="prim-input-desc">Identifies the verified submission to settle against.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">submission_id</div><div class="prim-input-type">bytes32</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Identifies the verified submission to settle against.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">task_id</div><div class="prim-input-desc">Source task identifier. Used to query escrow balance.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">task_id</div><div class="prim-input-type">bytes32</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Source task identifier. Used to query escrow balance.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">agent_address</div><div class="prim-input-desc">Worker agent''s receiving address. Must match registered agent.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">agent_address</div><div class="prim-input-type">address</div><div class="prim-input-req req">required</div><div class="prim-input-desc">Worker agent''s receiving address. Must match registered agent.</div></div>')
$content = $content.Replace('<div class="prim-input-row"><div class="prim-input-name">attestation_hash</div><div class="prim-input-desc">On-chain attestation hash from verify-proof. Validated before release.</div><div class="prim-input-req req">required</div></div>', '<div class="prim-input-row"><div class="prim-input-name">attestation_hash</div><div class="prim-input-type">bytes32</div><div class="prim-input-req req">required</div><div class="prim-input-desc">On-chain attestation hash from verify-proof. Validated before release.</div></div>')

[System.IO.File]::WriteAllText($path, $content, [System.Text.Encoding]::UTF8)
